# Generated by Django 5.0.6 on 2024-07-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0007_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
