# Generated by Django 5.0.6 on 2024-07-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0009_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
