# Generated by Django 5.0.6 on 2024-07-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0012_cartproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartproduct',
        ),
    ]
